### ISSUE TITLE
fail to import .cdf file into mzmine

### ISSUE THREAD

**Issue by AnaKovacic** [mzmine/mzmine3#1045]
### Basic information

* My operating system: windows 10 enterprise 2016 LTSB
* My MZmine version: mzmine 3.3.0

### What happened

* I have analysed the data on SynaptXS, than I have convert the files in MassLynx, Databridge from .raw to .cdf in order to make lockspray correction. 
* When I was trying to import one .cdf file into mzmine to see if it works, it gave me error attached: 
* Do you have any idea how I can fix it? 
Thank you.
Best, Ana
<img width="1738" alt="error mzmine cdf file" src="https://user-images.githubusercontent.com/72231221/208101609-aaf08634-369f-450f-889e-b92b81c84686.PNG">

**Comment by tomas-pluskal** [comment]
Could you please upload the .cdf file somewhere so we can take a look at it?

**Comment by AnaKovacic** [comment]
Yes, sure, but I have also figured out how I can do the lockspray
correction differently while still staying in the .raw file which shouldn't
be a problem for import.

Thank you.
Best
Ana
 21112022_AK_05_NPMIX_MSE_POS_RES01.CDF
<https://drive.google.com/file/d/1_Edx8TAmPsc8Bcb4hIet74Pu2Qtj01WO/view?usp=drive_web>

**Comment by tomas-pluskal** [comment]
Well, that's great, but it doesn't fix the problem in MZmine cdf import.

**Comment by AnaKovacic** [comment]
This is true, though better to avoid non-needed conversions.
Do you perhaps know how can you convert from cdf into for example xzML?
Thank you.
Ana

**Comment by robinschmid** [comment]
.raw? why dont you convert directly to mzML with msconvert

**Comment by AnaKovacic** [comment]
Hi,

because I have to do the mass correction, if not there is quite a
difference in spectra, and I haven't found a way how I would do the mass
correction in mzmine.
Thus, I have performed the mass correction with MassLynx (databridge), the
generated files are FAMM.raw and I was able to import the files, however,
it gave me the error:
"The retention time of scan #xxx is smaller than the retention time of the
previous scan. Please make sure you only use scans with increasing
retention times."
Because of that, I have used the Crop filter module and made separate mass
detection and chromatogram builder for ms1 and ms2, but this is
inconvenient since then you have only ms1 or only ms2.
Do you perhaps have a better suggestion on how to be able to perform mass
detection and chromatogram builder after mass correction?

I have also tried to convert the mass-corrected files into mzML, but then I
get the error attached.
Thank you.
Ana

**Comment by AnaKovacic** [comment]
Please find also the .raw and mass corrected .rawfile
https://drive.google.com/drive/folders/14cvkemzQD7rh9c3Su0wct7wq6UymMl3a?usp=sharing,
https://drive.google.com/drive/folders/1fZtXztTPW1EXNdeozRpLY4iyrjtX4JZI?usp=sharing

Thank you for your help.
Ana

**Comment by robinschmid** [comment]
I just pushed a fix for the CDF import. Your first file now works for me. 

You will find the development version here in a few minutes:
https://github.com/mzmine/mzmine3/releases/tag/Development-release

**Comment by AnaKovacic** [comment]
Thank you for your help.
I still haven't been able to build a chromatogram in mzmine, although using
different ways of data import, conversion with different software, and mass
correction. I am now running the analysis in different acquisitions and
with mass correction while acquiring the data. I will come back for your
help only in case none of the options will work.

Thank you.
Ana

**Comment by AnaKovacic** [comment]
Hi,

After running different acq., profile, centroid, with and
without mass correction within the run I was still not able to build the
chrom.
Please see the errors attached.
Do you have any idea, how can I do the chrom. builder with .raw files?
Working with .raw from waters from the first time, while not having such
kind of problems with other .raw so far.
Thank you.
Ana

**Comment by SteffenHeu** [comment]
Have you tried this to convert your files? https://github.com/AnP311/Waters2mzML

**Comment by AnaKovacic** [comment]
No, seems promising, I will try it!
Thank you.
