### ISSUE TITLE
GCMS spectral deconvolution

### ISSUE THREAD

**Issue by NthlLcrmp** [mzmine/mzmine3#925]
### Basic information

* My operating system: Windows 10 version 21H1
* My MZmine version: 3.2.8

### What happened

I try to perform spectral deconvolution on GCMS data.

Whether I use Hierarchical Clustering or Multivariate curve resolution algorithm, the preview doesn't work.

With Hierarchical clustering algorithm, the cluster list is empty :
![image](https://user-images.githubusercontent.com/114736047/193242325-a7adbcf6-4753-4390-be28-33cf1d51a84a.png)

With Multivariate curve resolution algorithm, I can choose the cluster but nothing happened :
![image](https://user-images.githubusercontent.com/114736047/193247230-0d297f96-2c80-4daa-a3fc-03ec8646a5ca.png)

I can go through spectral deconvolution with Multivariate curve resolution algorithm but not with Hierarchical Clustering algorithm where the following error appears (which was already reported in issue #744) :
![image](https://user-images.githubusercontent.com/114736047/193243428-bc490d63-9b01-4894-af5f-796e17776239.png)

**Comment by asmirn1** [comment]
@NthlLcrmp Could you upload your .mzmine project file or raw data files, so I could reproduce the error?

**Comment by NthlLcrmp** [comment]
Here is a link to download the project and the raw file :
https://filesender.renater.fr/?s=download&token=918d091b-95ce-44b9-b0ee-620ad1377786

**Comment by asmirn1** [comment]
@NthlLcrmp We have fixed a few issues with the Spectral Deconvolution in the version of MZmine. I have tested it with your project file, and it is working for me now.

Could you try the latest development build of MZmine from here: https://github.com/mzmine/mzmine3/releases/tag/Development-release

Let us know if it's working for you or not.

Alex

**Comment by NthlLcrmp** [comment]
Thanks Alex for your help.

This is better with this version. Spectral deconvolution with the Multivariate curve resolution algorithm is now working. However, I still have issue with the Hierarchical clustering algorithm. I can select feature and cluster, and I can preview the first clustering but not the second : 
![image](https://user-images.githubusercontent.com/114736047/193753565-fe80168b-a445-4236-af06-0eb3feae44ac.png)


And when I try to run it anyway  I still have an 'Unknown error' : 
![image](https://user-images.githubusercontent.com/114736047/193753900-cb025924-7bd1-4f8c-8f59-41d89a660226.png)

Could this be due to the chosen parameters ?

Nathalie

**Comment by ajburx** [comment]
I'm having this same issue. I'm using the latest developer build and the multivariate curve algorithm now works, as above. The hierarchical clustering GC deconvolution is also not working for me (same as above user).
Additionally, after multivariate curve deconvolution is completed, when trying to save the project or run GC alignment algorithms, I receive errors:

Saving project:
![image](https://user-images.githubusercontent.com/66914460/194572349-efd910d6-e7e2-4434-8d31-a0e3d8f998ad.png)

ADAP Alignment: 
![image](https://user-images.githubusercontent.com/66914460/194571596-779e982f-bac5-4f6c-bbb5-5cd5cf35b259.png)

Hierarchical cluster alignment: 
![image](https://user-images.githubusercontent.com/66914460/194572559-bf8f5d0a-1396-43b6-bb8d-8fd0fa4c04dc.png)

Thank you

**Comment by asmirn1** [comment]
@SteffenHeu @robinschmid I've made a pull request with fixes for this issue. Do you have any additional questions/comments, or we can merge the changes to the master branch?

@ajburx I've fixed the issues that @NthlLcrmp mentioned. I'll let you know when they are propagated to the developer build. 

I'll take a look at the alignment.

**Comment by robinschmid** [comment]
Reviewed and only a small comment

**Comment by robinschmid** [comment]
Just merged - the next development release contains the fix

**Comment by robinschmid** [comment]
Lets create new issues for remaining things

**Comment by adriherar** [comment]
Dear developers,

I'm having the same problems as the two users above with the hierarchical clustering from the spectral deconvolution GC.

![image](https://user-images.githubusercontent.com/116106346/196501066-89ae4afd-a791-4764-958f-f091978c72b3.png)

![image](https://user-images.githubusercontent.com/116106346/196501362-aae75332-00e8-4e42-8f31-53eb097cf9d6.png)

![image](https://user-images.githubusercontent.com/116106346/196501653-fce5eefe-1876-4ede-be3c-041cce67aeac.png)

I'm using the last version of MZMine and I'm working on windows 11. Could you please help me find what's going on?

Thank you in advance.

Adrián

**Comment by adriherar** [comment]
> @adriherar Could you try the latest development build and let us know whether it works for you or now: https://github.com/mzmine/mzmine3/releases/tag/Development-release
> 
> We fixed a few GC-related issues in it.
> 
> Alex

Dear @asmirn1

Thank you for your kind reply.

I did it with the latest version, as you recommended me, and it worked. However, after I did the normalization (with the linear normalization) and tried to align with the ADAP aligner GC, appeared an unknown errror as you could see in the picture below.

![image](https://user-images.githubusercontent.com/116106346/196991082-533d5796-4eb7-4249-a229-c5fad728dea4.png)

I'm about two steps before I could finish the data processing with this MZmine 3 version.

I'll be waiting for your kind reply.

Hoping you the best.

Adrián Hernández

**Comment by asmirn1** [comment]
@tnguy271

Have we fixed the alignment issue or we are still working on it?

**Comment by tnguy271** [comment]
@asmirn1 Yes it has been fixed. I have made a pull request with the fixes for alignment issue. @SteffenHeu @robinschmid Could you let us know if it's ready to be merged?

**Comment by adriherar** [comment]
> @asmirn1 Yes it has been fixed. I have made a pull request with the fixes for alignment issue. @SteffenHeu @robinschmid Could you let us know if it's ready to be merged?

Hello guys,

The alignment problem persists with the latest MZmine version (3.2.39) 

![image](https://user-images.githubusercontent.com/116106346/199136580-1616e6a0-070d-4b11-aafc-daa32fc5ef84.png)

Kind regards.

Adrián H.

**Comment by asmirn1** [comment]
@adriherar We've made some fixes for the alignment in development version: https://github.com/mzmine/mzmine3/releases/tag/Development-release

Could you try it?

**Comment by adriherar** [comment]
> @adriherar We've made some fixes for the alignment in development version: https://github.com/mzmine/mzmine3/releases/tag/Development-release
> 
> Could you try it?

Hello @asmirn1 

Thank you for your reply.

I've downloaded the latest version and It is not working yet.

![image](https://user-images.githubusercontent.com/116106346/200191219-9cb224af-e144-4fbc-80e1-2045391f4c6b.png)

I'll be waiting for your comments.

Greetings.

Adrián

**Comment by asmirn1** [comment]
@adriherar Could you attach your MZmine project file here (or upload it on Google Drive, etc.), so we could reproduce the error?

Alex

**Comment by adriherar** [comment]
> @adriherar Could you attach your MZmine project file here (or upload it on Google Drive, etc.), so we could reproduce the error?
> 
> Alex

Hello Alex,

I can´t save the project after the linear normalization process. I'll place the link with the project until the hierarchical clustering. [[https://drive.google.com/file/d/1LHPtpN_3eM672rRcyDWvmNrFy-DNdTSv/view?usp=share_link]](url)

What I do after normalization (parameters are set in the third picture) is the alignment using the adapt aligner GC, the parameters are set in the fourth picture. Finally, for the gap filling, I set the parameters as you can see in the fifth picture.

Please let me know if you have any trouble with the link.

![image](https://user-images.githubusercontent.com/116106346/200456971-8a07cc42-584e-4c82-9925-34c26795367c.png)

![image](https://user-images.githubusercontent.com/116106346/200457337-7352de84-0df1-47aa-93ce-b7080b97d50f.png)

![image](https://user-images.githubusercontent.com/116106346/200457782-7221d852-5dac-4979-bf38-d2118acf8127.png)

![image](https://user-images.githubusercontent.com/116106346/200457595-022abb8a-b91c-4b8c-abda-be62b62921a2.png)

![image](https://user-images.githubusercontent.com/116106346/200458029-3246b062-57b2-44a1-b81b-27bab982b240.png)


Greetings

Adrián

**Comment by asmirn1** [comment]
@adriherar 

Thank you for a detailed description. We'll test it on your data.

Alex

**Comment by tnguy271** [comment]
@adriherar 
We fixed the alignment issue. Could you try it again? 
Toan

**Comment by adriherar** [comment]
> We fixed the alignment issue. Could you try it again?

@tnguy271 

Thank you for your message. 

As an update, now I can save the project after the normalization. I could also use the alignment (first picture) but when I set gap filling there's an issue using the peak finder (second pic).

Finally, when I was trying to save the project until the alignment part, appears a problem (third picture).

I'm attaching the file until the normalization part: [https://drive.google.com/file/d/1LHPtpN_3eM672rRcyDWvmNrFy-DNdTSv/view?usp=share_link](url)

I'll be waiting for your kind reply.

![image](https://user-images.githubusercontent.com/116106346/200709085-a66f300f-158b-4e64-83cf-db4aef5e39fc.png)

![image](https://user-images.githubusercontent.com/116106346/200709280-1253183b-e545-4058-83de-68f075073628.png)

![image](https://user-images.githubusercontent.com/116106346/200711557-b8a0b089-a789-451c-939a-1520255f2de0.png)

**Comment by tnguy271** [comment]
hi @adriherar, Can you try the latest development version? Please let me know if you're still facing problems.

**Comment by adriherar** [comment]
> hi @adriherar, Can you try the latest development version? Please let me know if you're still facing problems.

Hi @tnguy271 thanx for your message.

Everything is great with the latest version. I have finished all the data processing (figure 1) and I can save the project at any time during the process. However, when I try to download the file in .CSV extension there is a problem (figure 2-4). 

When we export the .cvs extension in the 2.53 version we use the following parameters (.csv file example figure 5):

1. Select the last file "Aligned feature list gap-filled" and add the filename.
2. Field separator “;”
3. Export common elements: Export row retention time. 
4. Export data file elements: PeakRT and Peak Area. (In the latest version it says Feature RT)
5. Identification separator “:" and then ok.

I'm adding the saved link of the project until the "Aligned feature list gap-filled" step. [https://drive.google.com/file/d/1LHPtpN_3eM672rRcyDWvmNrFy-DNdTSv/view?usp=share_link](url)

This will be the final step to start using the MZmine3 version. 

Thank you for your time and I'll be waiting for your kind reply.

![image](https://user-images.githubusercontent.com/116106346/202062165-e90c2719-6312-499d-893d-8b5c3aa4e2b1.png)

![image](https://user-images.githubusercontent.com/116106346/202062351-14f44ee8-0387-4072-bd75-46893d5d8400.png)

![image](https://user-images.githubusercontent.com/116106346/202062568-58ba6914-6007-4436-8096-5158c6c8c0fa.png)

![image](https://user-images.githubusercontent.com/116106346/202062604-ffcb4210-7bbf-4d1a-858e-6987355addf6.png)

![image](https://user-images.githubusercontent.com/116106346/202063126-15a8250a-9a1b-4537-a39a-4c8a028503c3.png)

**Comment by tnguy271** [comment]
@SteffenHeu @robinschmid Is this an issue with export module? could you have a look? Thank you

**Comment by adriherar** [comment]
Hello there,

I'm still facing problems exporting the .CSV file with the 3.2.54 version.

Thank you in advance for your help.

![image](https://user-images.githubusercontent.com/116106346/202574193-1410ab11-e25e-40b4-a468-d5678cf04b34.png)
