### ISSUE TITLE
Error in alignment & saving of GCMS data

### ISSUE THREAD

**Issue by ajburx** [mzmine/mzmine3#948]
### Basic information

* My operating system: Windows 10 Enterprise x64
* My MZmine version: 3.2.32

### What happened

After successful hierarchical deconvolution of GCMS data files I am unable to save the MZmine project or carry out alignment using ADAP aligner (GC). Screenshots of errors are attached. I am unable to upload MZmine project file as I cannot save one, however a raw data file link is below. I'm not able to generate a log as the program crashes at the error

[Raw data](https://we.tl/t-zuTVrLd8mu)

Error when saving:
![Saving error](https://user-images.githubusercontent.com/66914460/195863336-338943db-9941-4147-a582-1530094cd937.PNG)

Error when running ADAP aligner:
![Alignment error](https://user-images.githubusercontent.com/66914460/195863405-466e69d9-1a2e-4774-a8de-4d2f2a0763a3.PNG)

**Comment by asmirn1** [comment]
@ajburx Could you try the latest development build: https://github.com/mzmine/mzmine3/releases/tag/Development-release

We fixed a few GC-related issues in it. Let us know whether it works for you or now.

Alex

**Comment by ajburx** [comment]
@asmirn1 Thank you for taking a look. I still have the save and alignment issue with the latest dev. build unfortunately.

**Comment by asmirn1** [comment]
@ajburx It turns out we are still working on fixing it. I'll let you know when it's fixed.

**Comment by gistamayo** [comment]
I just got time till yesterday to test the version of the link above (3.2.39). SD runs OK, but now I cannot export mgf file for GNPS using the option of GNPS-ADAP (GC-MS) provided. Any idea why? It gives the following message:
![Screen Shot 2022-11-02 at 13 47 33](https://user-images.githubusercontent.com/111382086/199588824-609b9061-6070-4670-aefe-61a41e87500f.png)

**Comment by gistamayo** [comment]
And I haven't used the correct alignment script. When using the one for GC, I get the same error as initially.
![Screen Shot 2022-11-02 at 14 02 43](https://user-images.githubusercontent.com/111382086/199591812-b8a34cc3-aedf-44de-92c9-f0b73d531c58.png)

**Comment by asmirn1** [comment]
@ajburx @gistamayo 

We've made some fixes for the alignment in development version: https://github.com/mzmine/mzmine3/releases/tag/Development-release

Could you try it?
